[k8s_master]
rhel-master ansible_host=192.168.1.28

[k8s_workers]
rhel-worker1 ansible_host=192.168.1.29
rhel-worker2 ansible_host=192.168.1.30

[k8s_all:children]
k8s_master
k8s_workers


[k8s_all:vars]
ansible_user=root
ansible_password=echo@TEST2026
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3.6
