- name: Configure firewall on all K8s nodes
  hosts: k8s_all
  become: true
  roles:
    - role: firewalld
      tags: firewalld

- name: Configure common K8s components on all nodes
  hosts: k8s_all
  become: true
  roles:
    - role: k8s-common
      tags: k8s-common

- name: Initialize Kubernetes master
  hosts: k8s_master
  become: true
  roles:
    - role: k8s-master
      tags: k8s-master
